version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ros-postgres
    environment:
      POSTGRES_USER: ros_user
      POSTGRES_PASSWORD: ros_password
      POSTGRES_DB: order_db
      POSTGRES_MULTIPLE_DATABASES: "order_db,user_db"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: ros-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: ros-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data: